name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    phpunit:
        name: Test on PHP ${{ matrix.php }} + Symfony ${{ matrix.symfony }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4' ]
                symfony: [ '6.*', '7.0.*', '7.1.*', '7.2.*' ]
                # exclude unsupported combos
                exclude:
                    # Symfony 7.2 requires PHP ≥ 8.2
                    - php: '8.1'
                      symfony: '7.2.*'
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, intl
                  coverage: none

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Update Symfony packages to ${{ matrix.symfony }}
              run: |
                  composer self-update --2
                  # adjust your Symfony components to the target version
                  composer require "symfony/framework-bundle:${{ matrix.symfony }}" \
                                   "symfony/translation:${{ matrix.symfony }}" \
                                   --no-interaction --update-with-all-dependencies

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --ansi

            - name: Run PHPUnit
              run: vendor/bin/phpunit --configuration phpunit.xml.dist --verbose
